site:
  description: Bruno de Paula Kinoshita personal web site
  pretty_urls: true
  title: Bruno P. Kinoshita
  css: site.css
  posts_per_page: 5
  root: /
  enable_debug_info: true
smartypants:
  enable: true
