site:
    title: Bruno P. Kinoshita
    description: 
    author: Bruno P. Kinoshita
    pretty_urls: true
    enable_gzip: true
    debug: true
    
smartypants:
    enable: true

server:
    config_variants: 
        default:
            site: 
                base_url: http://localhost/kinoshita.eti.br/
        live: 
            site: 
                base_url: http://localhost:8080/

baker:
    skip_patterns:
        - /^index.php/
    config_variants:
        default:
            site:
                base_url: http://localhost/kinoshita.eti.br/blog/
        production: 
            site: 
                base_url: http://www.kinoshita.eti.br/